
functions:
  "bootstrap mongo-orchestration":
    - command: subprocess.exec
      params:
        binary: sh
        args:
          - ${DRIVERS_TOOLS}/.evergreen/run-orchestration.sh
        include_expansions_in_env:
          - DRIVERS_TOOLS
          - TOPOLOGY
          - MONGODB_VERSION
          - MONGODB_BINARIES

  "prepare resources":
    - command: subprocess.exec
      params:
        working_dir: mongosql-rs
        include_expansions_in_env:
          - DRIVERS_TOOLS
        binary: bash
        args:
          - ./evergreen/fetch-drivers-tools.sh

  "stop mongo orchestration":
    - command: shell.exec

      params:
        include_expansions_in_env:
          - DRIVERS_TOOLS
          - MONGO_ORCHESTRATION_HOME
          - PROJECT_DIRECTORY
        script: |
          ${PREPARE_SHELL}

          cd ${MONGO_ORCHESTRATION_HOME}
          # source the mongo-orchestration virtualenv if it exists
          if [ -f venv/bin/activate ]; then
            . venv/bin/activate
          elif [ -f venv/Scripts/activate ]; then
            . venv/Scripts/activate
          fi
          mongo-orchestration stop
