[package]
name = "data-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "3"
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
